name: 'Release Attachment Metadata'
description: 'Publish updates about release binaries.'
inputs:
  token:  # Github authorized Token
    description: 'An authorized GitHub token.'
    required: true
  owner:
    description: 'The owner of the target project.'
    required: false
    default: ""
  repo:
    description: 'The target project.'
    required: false
    default: ""
  outFile:
    description: 'The name of a file to save release JSON data.'
    required: false
    default: "release-history.json"
  outBranch:
    description: 'The branch name to push the generated file into'
    required: false
    default: "release-data"
  releaseTag:
    description: 'Optionally pass a specific release tag, instead of latest.'
    required: false
    default: ""
  maxReleases:
    description: 'The amount of historic releases that should be tracked'
    required: false
    default: "10"

outputs:
  latest_release:
    description: 'The latest release tag.'
  data_json:
    description: 'The release data, JSON-encoded.'
  is_released:
    description: 'Returns "true" if the latest release is a non-prerelease, non-draft.'

runs:
  using: 'node12'
  main: 'index.js'
